### ISSUE TITLE
Composite SM and visit_current_states

### ISSUE THREAD

**Issue by reid-p** [boost-experimental/sml#109]
How do you visit the current state of sub sm in a composite sm.

  stdstr State;
  sm.visit_current_states([&](auto state) {
    State += state.c_str();
  });

Above code only reveturn the state of the top level sm.
For debug purposesI'd like to dump the sub state machine state when it's running.

**Comment by LegendLukaz** [comment]
I am also stuck on a similar situation while using sm.is(), hoping to receive an answer to this soon.

**Comment by Ahalperin** [comment]
you should use logging policy if logging for debug is your need.
refer to [http://boost-experimental.github.io/sml/examples/index.html#logging](url)

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-experimental/sml/commit/1a46dbf272d231f44afe09093b525646f675ecfc
