### ISSUE TITLE
Anonymous namespace warning when using composite state

### ISSUE THREAD

**Issue by vekkt0r** [boost-experimental/sml#112]
g++ (5.4.0) throws warning `boost::sml::v1_1_0::concepts::composable<Sub>’ has a base '...' whose type uses the anonymous namespace` when using action or guard lambda from global scope in a composite state. Clang does not seem to show this warning.

Is this supported without having lambda directly in transition table? Am I doing something wrong?

```c++
#include "sml.hpp"

namespace sml = boost::sml;

auto Action = []{};

struct Sub {
  auto operator()() noexcept {
    using namespace sml;
    return make_transition_table(
        *"Init"_s / Action = X);
  }
};

struct Top {
  auto operator()() noexcept {
    using namespace sml;
    return make_transition_table(
        *"Init"_s = state<Sub>);
  }
};

int main(int argc, char *argv[])
{
  sml::sm<Top> sm;
  return 0;
}
```

**Comment by kptlronyttcna** [comment]
I have this problem too.

**Comment by Bagira80** [comment]
The problem seems to be unrelated to composite states.
Your example from above can even be simplified to the following and still triggers the same warning.
```cpp
#include "boost/sml.hpp"

namespace sml = boost::sml;

auto Action = []{};

struct Sub {
  auto operator()() noexcept {
    using namespace sml;
    return make_transition_table(
        *"Init"_s / Action = X);
  }
};

int main()
{
  sml::sm<Sub> sm;
  return 0;
}
```

The warning depends on `Action` and how or where it is implemented:

```cpp
#include "boost/sml.hpp"

namespace sml = boost::sml;

auto     action1 = []{};
#define  action2   []{}
struct   Action3 { void operator() (){}; } action3;
struct           { void operator() (){}; } action4;

struct Sub {
  auto operator()() noexcept {
 
    auto action5 = []{};
    
    using namespace sml;
    return make_transition_table(
        *"Init"_s / action1 = X    // triggers warning
    //  *"Init"_s / action2 = X    // triggers NO warning
    //  *"Init"_s / action3 = X    // triggers NO warning
    //  *"Init"_s / action4 = X    // triggers warning
    //  *"Init"_s / action5 = X    // triggers NO warning
    );
  }
};

int main()
{
  sml::sm<Sub> sm;
  return 0;
}
```
Try to use each of the five actions individually (by commenting all the other lines in the transition-table) and you will realize that `action1` and `action4` are the only ones that trigger the warning.

However, I cannot really tell why.

**Comment by Bagira80** [comment]
OK, I looked into the latest C++ standard and as far as I understand `action1` and `action4` have *no linkage* which is the reason for the warning. It would not be safe to use `action1` and `action4` from within another translation-unit.
Whether GCC should trigger this warning if the code from above is in a single `*.cpp` file is debatable.

Of course, the warning message is entirely misleading, too.
(See also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53184 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51440)

**Comment by krzysztof-jusiak** [comment]
Fixed in https://github.com/boost-experimental/sml/pull/162 by adding an anonymous namespace to the examples. This way ODR rule is not violated for guards/actions implemented using lambdas in a header file.

```cpp
#include <boost/sml.hpp>

namespace sml = boost::sml;

namespace { // fix for the ODR warning

auto     action1 = []{};
#define  action2   []{}
struct   Action3 { void operator() (){}; } action3;
struct           { void operator() (){}; } action4;

struct Sub {
  auto operator()() noexcept {
 
    auto action5 = []{};
    
    using namespace sml;
    return make_transition_table(
        *"Init"_s / action1 = X    // triggers warning
    //  *"Init"_s / action2 = X    // triggers NO warning
    //  *"Init"_s / action3 = X    // triggers NO warning
    //  *"Init"_s / action4 = X    // triggers warning
    //  *"Init"_s / action5 = X    // triggers NO warning
    );
  }
};

}

int main()
{
  sml::sm<Sub> sm;
  return 0;
}
```

Full example here -> https://godbolt.org/g/Ak6dht
