### ISSUE TITLE
[Feature-Request] Allow actions/guards to take base-class of injected dependency.

### ISSUE THREAD

**Issue by Bagira80** [boost-experimental/sml#116]
Actions/Guards can not only take the currently processing event as argument but also dependencies injected into the state-machine.

Example 1:
```cpp
struct Base{};
struct Derived : Base {};

auto action1 = [](const auto& event, Derived& obj)
{
    // do something with "obj"
}

// ...

Derived myDerived;
sm<MyTransitionTable> statemachine{myDerived};
```

**However, trying to match the base-class of an injected dependency seems not to work.**

Example 2:
```cpp
struct Base {};
struct Derived : Base {};

auto action1 = [](const auto& event, Base& obj)
{
    // do something with "obj", possibly upcasting it to Derived.
}

// ...

Derived myDerived;
sm<MyTransitionTable> statemachine{myDerived};  // triggers static_assert
// sm<MyTransitionTable> statemachine{static_cast<Base&>(myDerived)};  // works
```
*Example 2* results in a compilation-error (static_assert) with the following message:
```console
...../boost/sml.hpp:316:3: error: static assertion failed: Type T has to be passed via constructor!
```

It would be great if example 2 could work without having to downcast the derived dependency type.

**Comment by krzysztof-jusiak** [comment]
Thanks, @Bagira80 for the idea, however, it's not SML which should handle such conversions to keep the single responsibility. What you need might be easily handled by dependency injection library, though - example here -> http://boost-experimental.github.io/sml/examples/index.html#dependency-injection.
