### ISSUE TITLE
state machine memory leak risk

### ISSUE THREAD

**Issue by justwillim** [boost-experimental/sml#119]
When I reviewing the code here : http://boost-experimental.github.io/sml/examples/index.html#states

```
// $CXX -std=c++14 actions_guards.cpp

#include <boost/sml.hpp>
#include <cassert>
#include <iostream>
#include <typeinfo>

namespace sml = boost::sml;
struct e1 {};
struct e2 {};
struct e3 {};
struct e4 {};
struct e5 {};

auto guard1 = [] {
  std::cout << "guard1" << std::endl;
  return true;
};

auto guard2 = [](int i) {
  assert(42 == i);
  std::cout << "guard2" << std::endl;
  return false;
};

bool guard3(int i) {
  assert(42 == i);
  std::cout << "guard3" << std::endl;
  return true;
}

auto action1 = [](auto e) { std::cout << "action1: " << typeid(e).name() << std::endl; };
struct action2 {
  void operator()(int i) {
    assert(42 == i);
    std::cout << "action2" << std::endl;
  }
};

struct actions_guards {
  auto operator()() noexcept {
    using namespace sml;
    return make_transition_table(
       *"idle"_s + event<e1> = "s1"_s
      , "s1"_s + event<e2> [ guard1 ] / action1 = "s2"_s
      , "s2"_s + event<e3> [ guard1 && ![] { return false;} ] / (action1, action2{}) = "s3"_s
      , "s3"_s + event<e4> [ !guard1 || guard2 ] / (action1, [] { std::cout << "action3" << std::endl; }) = "s4"_s
      , "s3"_s + event<e4> [ guard1 ] / ([] { std::cout << "action4" << std::endl; }, [this] { action4(); }) = "s5"_s
      , "s5"_s + event<e5> [ call(guard3) || guard2 ] / call(this, &actions_guards::action5) = X
    );
  }

  void action4() const { std::cout << "action4" << std::endl; }

  void action5(int i, const e5&) {
    assert(42 == i);
    std::cout << "action5" << std::endl;
  }
};

int main() {
  sml::sm<actions_guards> sm{42};
  sm.process_event(e1{});
  sm.process_event(e2{});
  sm.process_event(e3{});
  sm.process_event(e4{});
  sm.process_event(e5{});
  assert(sm.is(sml::X));
}

```

in these two line :
```
      , "s3"_s + event<e4> [ guard1 ] / ([] { std::cout << "action4" << std::endl; }, [this] { action4(); }) = "s5"_s
      , "s5"_s + event<e5> [ call(guard3) || guard2 ] / call(this, &actions_guards::action5) = X
``` 

It indicate that we could pass this pointer to the transition table. But it is wrong.

because, in sm_impl struct, when finish initialized the member 
```
transitions_t transitions_
```
the actions_guards or other state machine struct will be distructed.

As a result, passing this pointer in a transition table will cause memory leak issue.

The sample code did not crash is because we have no member data in this structure, and the same is not complex enough to let memory issue crash itself.

**Comment by krzysztof-jusiak** [comment]
you are right @justwillim, I have a fix for that, just haven't pushed it yet. The solution is to store the object which has the transition table  (if its' not empty) and change the move constructor of the sm. I'll push the fix soon, great spot, though 👍

**Comment by krzysztof-jusiak** [comment]
Storing the object which owns the transition table has also a benefit of having local data per state machine, which is handy when you deal with all of them.

**Comment by justwillim** [comment]
Thanks, looking forward to your patch greatly

**Comment by krzysztof-jusiak** [comment]
Thanks, @justwillim. It's fixed by https://github.com/boost-experimental/sml/commit/2e07f38895629e5198c625fe01aaff1891551a78. If the transition table has members it will be stored. That also allows having data per state machine.
