### ISSUE TITLE
Compilation error sml.hpp

### ISSUE THREAD

**Issue by didierjeanphi** [boost-experimental/sml#126]
I tried to install and compile a program with SML and I get this error

**[]/include/boost/sml.hpp:166:8: error: previous definition of ‘struct boost::sml::v1_1_0::aux::function_traits<R (T::*)(TArgs ...)>’**

Have I done something wrong?

**Comment by didierjeanphi** [comment]
Me again...
I think the following code does not work with -std=1z 

c++`template <class>
struct function_traits;
template <class R, class... TArgs>
struct function_traits<R (*)(TArgs...)> {
  using args = type_list<TArgs...>;
};
template <class R, class... TArgs>
struct function_traits<R(TArgs...)> {
  using args = type_list<TArgs...>;
};
template <class R, class T, class... TArgs>
struct function_traits<R (T::*)(TArgs...)> {
  using args = type_list<TArgs...>;
};
template <class R, class T, class... TArgs>
struct function_traits<R (T::*)(TArgs...) const> {
  using args = type_list<TArgs...>;
};
#if __cplusplus > 201402L
template <class R, class... TArgs>
struct function_traits<R (*)(TArgs...) noexcept> {
  using args = type_list<TArgs...>;
};
template <class R, class... TArgs>
struct function_traits<R(TArgs...) noexcept> {
  using args = type_list<TArgs...>;
};
template <class R, class T, class... TArgs>
struct function_traits<R (T::*)(TArgs...) noexcept> {
  using args = type_list<TArgs...>;
};
template <class R, class T, class... TArgs>
struct function_traits<R (T::*)(TArgs...) const noexcept> {
  using args = type_list<TArgs...>;
};
#endif`
As you can see with 1z the macro __cplusplus is defined to a value greater than 201402L (under gcc).. which means that we end up having a dpulication in the definition of function traits.

**Comment by Bagira80** [comment]
This should not be an error.
It just shows the lack of your compiler to fully support C++17.

`__cplusplus` should be defined to a value greater than `201402L` if compiled with support for a C++-standard greater than C++14.
And C++17 treats the `noexcept` keyword as a part of the function signature, therefore it requires the additional template-specializations.

What compiler and version of it are you using?
I can confirm that GCC 7.1 compiles fine with these settings when used with `-std=c++1z`.

**Comment by didierjeanphi** [comment]
Bagira80,
thanks for your reply. I compile also with gcc-7.1 and this works fine... However, for my project I also need to provide support for gcc-6.3  this is why I raised that issue.

**Comment by Bagira80** [comment]
After Kris merged my pull-request #127 this should no longer be an issue for GCC 6.

**Comment by didierjeanphi** [comment]
Thanks a lot Deniz.
