### ISSUE TITLE
BOOST_SML_DISABLE_EXCEPTIONS && MSVC

### ISSUE THREAD

**Issue by reid-p** [boost-experimental/sml#134]
This macro defintion doesn't work for MSVC.

`#define BOOST_SML_DISABLE_EXCEPTIONS !(defined(__cpp_exceptions) || defined(__EXCEPTIONS))`

MSVC doens't seem to predefine either `__cpp_exceptions` or `__EXCEPTIONS`

MSVC preprocessor doesnt seem to handle the following evaluation correctly.

`#if BOOST_SML_DISABLE_EXCEPTIONS`

Using the following does seem to do the correct thing:

```
#if !defined(BOOST_SML_DISABLE_EXCEPTIONS)  
#if !(defined(__cpp_exceptions) || defined(__EXCEPTIONS) || defined(_CPPUNWIND)) 
#define BOOST_SML_DISABLE_EXCEPTIONS 1 
#else                                                                          
#define BOOST_SML_DISABLE_EXCEPTIONS 0           
#endif                                                                         
#endif                                                                  
```

**Comment by reid-p** [comment]
duh..
I hadn't merged master to see this most of this had been fixed.

But I still need `|| defined(_CPPUNWIND)`

**Comment by reid-p** [comment]
And from the boost/config/compiler/visualc.hpp for comparison

```
// check for exception handling support:
#if !defined(_CPPUNWIND) && !defined(BOOST_NO_EXCEPTIONS)
#  define BOOST_NO_EXCEPTIONS
#endif
```

**Comment by krzysztof-jusiak** [comment]
Thanks, @reid-p. To be fixed by -> https://github.com/boost-experimental/sml/pull/155
