### ISSUE TITLE
How to avoid delegating member functions for guards

### ISSUE THREAD

**Issue by Zlatan1988** [boost-experimental/sml#137]
Hi,

I read https://github.com/boost-experimental/sml/issues/93 and want add a guard to this example.

```
#include <iostream>
#include <boost/sml.hpp>

namespace sml = boost::sml;

struct ev1 {};
struct with_prop;

struct table {
    auto operator()() const noexcept {
        using namespace sml;
        return make_transition_table(
            *"s1"_s  + event<ev1>
            [([](with_prop& p) {
            [](auto& p) -> bool {
                std::cout << "on_entry:guard" << std::endl;
                return p.guard();
            }(p);
            })]
            /
            [](with_prop& p) {
                [](auto& p) -> void {
                    std::cout << "on_entry:action" << std::endl;
                    p.method1();
                }(p);
            }
        );
    }
};
struct with_prop {
    with_prop() : sm(*this) {}

    template <typename Event>
    void process_event(Event&& ev) {
        sm.process_event(std::forward<Event>(ev));
    }

    void method1() {
        std::cout << "method1" << std::endl;
    }
    void method2() {
        std::cout << "method2" << std::endl;
    }

    bool guard() {
       std::cout << "guard" << std::endl;
       return true;
    }

private:
    sml::sm<table> sm;
};

int main() {
    with_prop wp;
    std::cout << "> Send Event1" << std::endl;
    wp.process_event(ev1());
    wp.method2();
}

```
Error:
``
use of 'static auto boost::sml::v1_1_0::front::call<TEvent, boost::sml::v1_1_0::aux::type_list<TArgs ...>, boost::sml::v1_1_0::back::no_policy>::execute(T, const TEvent&, TSM&, TDeps&, TSubs&) [with T = boost::sml::v1_1_0::aux::zero_wrapper<table::operator()() const::<lambda(with_prop&)>, void>; TSM = boost::sml::v1_1_0::back::sm_impl<boost::sml::v1_1_0::back::sm_policy<table> >; TDeps = boost::sml::v1_1_0::aux::pool<with_prop&>; TSubs = boost::sml::v1_1_0::aux::pool<boost::sml::v1_1_0::back::sm_impl<boost::sml::v1_1_0::back::sm_policy<table> > >; TEvent = ev1; Ts = {with_prop&}]' before deduction of 'auto'
``

Is there any good way to use the guards with delegating member functions? How can I avoid this error?

Thanks for the help!

**Comment by redboltz** [comment]
@Zlatan1988 , this is not a solution of your question but it might be useful.
Why do you want to use `with_prop`? In my case #93, I want to call process_event in action handlers.
If your reason is the same, you don't need to use dependency mechanism such as `with_prop`.
See https://github.com/boost-experimental/sml/issues/94#issuecomment-310989485.
https://wandbox.org/permlink/5JiWphg7w78VizbK 

Be careful about #96 and #113. sml still have some unexpected action order.

**Comment by redboltz** [comment]
@Zlatan1988 , I found the solution for you question.
See https://wandbox.org/permlink/eZ813UwG0YQsgK4Q
It's function object approach.
See https://github.com/boost-experimental/sml/issues/93#issuecomment-283629397

I'm not sure the instantiation timing of nested lambda expression. 
My #93 nested lambda code works on g++ 7.2.0
https://wandbox.org/permlink/LFjJfz2W4ayWs690
but got compile error on clang++
https://wandbox.org/permlink/LFjJfz2W4ayWs690

Perhaps the instantiation is implementation defined.

**Comment by redboltz** [comment]
> but got compile error on clang++
> https://wandbox.org/permlink/omCLBzjZuLeWcuQl
> 
> Perhaps the instantiation is implementation defined.

When I set `-std=c++14`, it successfully compiled.
https://wandbox.org/permlink/labBCx2XZXD22fhY

And back to your original question, you just need to insert `return` statement to the inner lambda expression:

Before
```c++
            [](auto& p) -> bool {
```

After
```c++
            return [](auto& p) -> bool {
```

```c++
        return make_transition_table(
            *"s1"_s  + event<ev1>
            [([](with_prop& p) {
            return [](auto& p) -> bool {
                std::cout << "on_entry:guard" << std::endl;
                return p.guard();
            }(p);
            })]
            /
            [](with_prop& p) {
                [](auto& p) -> void {
                    std::cout << "on_entry:action" << std::endl;
                    p.method1();
                }(p);
            }
        );
```

gcc 7.2.0
https://wandbox.org/permlink/ZjJ60m0g3IFCuuhk
and clang 5.0.0
https://wandbox.org/permlink/hc6mtlAIgpnncqaJ
both successfully compiled.

**Comment by Zlatan1988** [comment]
@redboltz Thank you very much! 

I'm new to lambda expression and your solution helped me a lot :-)
