### ISSUE TITLE
Example from readme cannot be compiled

### ISSUE THREAD

**Issue by ooxi** [boost-experimental/sml#167]
When trying to access the readme's [godbolt](https://godbolt.org/g/sNfLzn) link, the compilation fails.

**Comment by kamibo** [comment]
Seems to work fine after removing "final" from "struct tcp_release".
https://godbolt.org/g/39HnsB

**Comment by SpyrosMourelatos** [comment]
So why this example still exists without a fix even with the issue marked as closed?
