### ISSUE TITLE
[feature] local transitions

### ISSUE THREAD

**Issue by krzysztof-jusiak** [boost-experimental/sml#17]
src ^ event [guard] / action = src
src ^ event [guard] / action = src(H)

**Comment by Ulenspiegel** [comment]
I wonder if it will make more sense to be able to define internal transitions from within composite state itself, not in the context of the containing state? As in, if transition originates from TopState into one of substates, then transition is defined in the context of TopState? Something like this:

```c++
struct TopState {
  auto configure() const noexcept {
    // ...
    return make_transition_table(
      // ...
      this + event<e1> = sub,
      sub(subsub) + event<e2> = this
    );
  }
};
```

Choice of `this` is arbitrary, of course.

**Comment by krzysztof-jusiak** [comment]
reference: http://stackoverflow.com/questions/14666095/uml-state-machines-local-vs-external-transition
Adding @viboes as his ticket was closed
