### ISSUE TITLE
Hot to reset sml::sm instance?

### ISSUE THREAD

**Issue by dsiroky** [boost-experimental/sml#176]
Hi! There is no dedicated method and both (copy/move) assignment operators are deleted so I can't use e.g. `state_machine = sml::sm<StateMachine>{}. What is a correct way to reset a sml state machine?

**Comment by lanhtao** [comment]
new (&state_machine) sml::sm<table>(std::forward<Args>(args)...)

**Comment by lanhtao** [comment]
It just re-invokes the constructor of sml. The parameters depend on the input of your constructor.

**Comment by AnthonyVH** [comment]
Note that if you do placement new, you have to first explicitly destruct the existing object. Otherwise you'll get undefined behavior, see e.g. https://stackoverflow.com/questions/39287330.

**Comment by lanhtao** [comment]
As you know, what does the instance of state machine need to do explicitly destruct or reset?

**Comment by AnthonyVH** [comment]
I'm afraid I don't know. Just wanted to warn @dsiroky about the potential pitfalls of using placement new.

**Comment by dsiroky** [comment]
I guess there is no "built in" way other then in place dtor/ctor. I'll create some pull request.
