### ISSUE TITLE
[Solved] How to pass parent class into the state machine struct?

### ISSUE THREAD

**Issue by LegendLukaz** [boost-experimental/sml#190]
Essentially, I want an action to edit a member variable within the outer class nesting the state machine struct.

``` C++
struct decisionMaker {
        cASM& parent_;

        auto operator()() const noexcept {
            using namespace sml;

            return make_transition_table(
                    idle(H) + event<start> / [] (const start& e) { LOG_INFO("Start signal received, starting at %d", e.maneuverID); } = running
                    , running + event<stop> / [] (const stop& e){ LOG_INFO("Stop signal received, stopping at %d", e.maneuverID);} = idle
                            , running + event<complete> / [&] () {parent_.Completed(); LOG_INFO("Completed the Circuit");} = idle
            );
        }
};
```
cASM is the outer class and i want to be able to call the function Completed() to update a private member variable in the outer class. Is that possible?

**Comment by cblauvelt** [comment]
@LegendLukaz  just out of curiosity, how was this solved?

**Comment by LegendLukaz** [comment]
This was solved by passing in the outer class when constructing the state machine.
``` C++
struct state_machine { ... };
sml::sm<state_machine> myStateMachine {*this};

```
and in the action using the outer class, I added a parameter that takes in a pointer to a class. Essentially, this method was mentioned in the tutorial and was paired with the tutorial on using dependency injection.

However, I ran into another problem where the code would not compile because of all the ```auto``` types that couldn't be resolved. Someone mentioned about how this is intrinsic to C++ and can only be avoided by doing out of class declarations, but this is just not possible since I must declare everything as a member of the class because of the constraint of the plugin system I am using.  It would be great actually if someone know the answer to this part.

**Comment by cblauvelt** [comment]
Thanks @LegendLukaz . I tried something similar with using a shared_ptr to the state machine and ran into exactly the same issue with the auto types. `error: invalid use of incomplete type 'struct TcpClientStateMachine::Actions'`.

**Comment by cblauvelt** [comment]
@LegendLukaz I wanted to let you know that I found a good set of examples for how to do this at https://github.com/ubeh/fsm_examples.

**Comment by LegendLukaz** [comment]
@cblauvelt thank you so much for the heads up! I did something similar, but with unique_ptr instead, but it wasn't particularly elegant. One problem I ran into when I tried to construct sub-machines is that I can't pass forward any reference/dependencies into the new submachine via the ```state<submachine>``` syntax. I will see whether the new code could help solve the problem.
