### ISSUE TITLE
Add entry/exit behavior within state definitions

### ISSUE THREAD

**Issue by Tal-seven** [boost-experimental/sml#218]
hi! with sml is it possible to add entry/exit behavior right into the definition of the concrete state like in msm. 

I have tried something like this but it doesnt work. 

```
struct connected  {
 
     template<class Event,class FSM>
     on_entry<sml::back::_,sml::back::initial>(Event& event,FSM& fsm)
     {
             std::cout << "Timer Started\n";
     }
};
```

**Comment by krzysztof-jusiak** [comment]
It's a design decision that entry/exit actions have to be explicit on the transition table. The MSM behavior could be provided by an extension though.
