### ISSUE TITLE
Generate State Machine Diagram from [Boost].SML

### ISSUE THREAD

**Issue by multivac61** [boost-experimental/sml#227]
First off, thank you for an incredibly useful library. I've been using it this summer for an embedded project and it's done magic to simplify the software architecture.

Around the net I have noticed a couple of pictures of state-machine diagrams that say "Generated with [Boost].SML" [such as this one](http://boost-experimental.github.io/sml/embo-2018/images/transition_table.png). I haven't however been able to figure out how to do this, could you be so kind to show me how?

All the best.

**Comment by sebkraemer** [comment]
Have a look at the documentation example  [plantuml-generation](https://boost-experimental.github.io/sml/examples/index.html#plant-uml-integration).

**Comment by krzysztof-jusiak** [comment]
Yeah, as @sebkraemer suggested, the easiest way to generate a diagram is to take a look at the plantuml generation example. SML is easy to parse as well so I can imagine a simple python script or even a regex which could generate a diagram too. Unfortunately, I don't have one handy ATM.

**Comment by lucaszanella** [comment]
link broken

**Comment by tiagobonetti** [comment]
> link broken

[plantuml-generation](https://boost-ext.github.io/sml/examples.html#plant-uml-integration)
