### ISSUE TITLE
Create branch for release

### ISSUE THREAD

**Issue by Warchant** [boost-experimental/sml#287]
Please, create branch for release v1.1.0

**Comment by krzysztof-jusiak** [comment]
v1.1.0 is already released and there is a tag for it already.
Please take a look at https://github.com/boost-experimental/sml/tree/v1.1.0.
Not sure what a release branch would offer over a tag?

**Comment by Warchant** [comment]
We use sml as a submodule, and we want to checkout to specific version. 
`git checkout v1.1.0` fails, because there is no branch for that tag (my guess).

**Comment by krzysztof-jusiak** [comment]
I just tried and it worked for me out of the box after `git submodule add https://github.com/boost-experimental/sml`, `git checkout v1.1.0`.

Maybe it's git a version (I'm using 2.21.0) or something?

I also found this thread on stack-overflow -> https://stackoverflow.com/questions/7500741/can-git-submodule-update-be-made-to-fetch-tags-in-submodules
