### ISSUE TITLE
Why is the logger dependency held by reference and not by value?

### ISSUE THREAD

**Issue by BenjaminW3** [boost-experimental/sml#299]
The state machine type is stored in the sm by value (copied in). The logger on the other hand is always stored by reference (`aux::type_list<logger_t &>`). I know that I can work around this by making sure that the logger lives longer than the state machine but why do I have to?
Is there any reason to handle the logger differently from the other dependencies? This is not intuitive and may lead to bugs.
In my case I created a stateful logger (as well as other dependencies) on the stack (within a class method) and created the state machine using this logger (and the dependencies). The state machine was stored as a member variable. Later when something should be logged, the application crashed, as the logger that was referenced was destroyed when it went out of scope.

**Comment by sdebionne** [comment]
Because it requires the logger to be Copyable which is probably not desirable?

For your use case where the sm is a member variable, something like this should work:

```cpp
struct foo
{
    foo() : m_fsm(m_logger) {}

    logger m_logger; // This must come first
    sm<...> m_fsm;
};
```

**Comment by BenjaminW3** [comment]
Yes, the logger not being copyable might be a reason.
As a workaround I did something similar to what you wrote.

My point is still that it is much too easy to shoot yourself into the foot and in the best case the interface should prevent you from doing such things.
