### ISSUE TITLE
Add state machine inheritance

### ISSUE THREAD

**Issue by viboes** [boost-experimental/sml#31]
While is is not clear that UML supports state machine inheritance, a state machine is associated to a class that support inheritance.

The kind of things that state machine inheritance should support is 
- able to refine(decompose) a specific state.
- able to refine a transition guard and/or action.
- when the target state has been refined, able to change the target state of a transition by an associated entry point.

**Comment by krzysztof-jusiak** [comment]
Any ideas for syntax here?
