### ISSUE TITLE
Using the library to manage ASIO objects and threads

### ISSUE THREAD

**Issue by pesho-t** [boost-experimental/sml#311]
Apologies if this isn't the correct place to ask for help. I've also asked the [same question on StackOverflow](https://stackoverflow.com/questions/58658616) but I figured also having this here increases my chances of getting an answer.

First of all, I'd like to clarify that by ASIO objects I mean a simple timer for the time being, but further down the line I want to create a state machine to deal with sockets and data transmission.

I have been exploring the library for about a few weeks now and trying out different things. I quite like it, however the documentation doesn't help in my use case and its source is not exactly inviting for someone still fairly new to metaprogramming.

For the time being, I'd like to create a state machine that manages an ASIO timer (to wait asynchronously). The interface would provide a start call where you can tell it how long it should wait, a cancel call (to cancel an ongoing wait), and some callback to be invoked when the timer fires.

I have already achieved this in one way, following both sml examples in [this repository][2] and it works well - I have a class which manages the timer and contains a state machine. The public interface provides means to inject the appropriate events into the FSM and query its state. The private interface provides means to start and stop the timer. The FSM class is a friend to the controller so it has access to the private functions.

However I was wondering if there is a way to take some of the controller functionality and move it into the FSM - it would hold all ASIO objects and run the io_context/io_service in a thread it has spawned.

(1) First problem I'd encounter is the fact that the state machine is copied - ASIO objects don't allow this, but this can be worked around by wrapping them in shared pointers.

(2) Next is, sending events to the FSM from within. I figured out how to do it from actions by obtaining a callable **boost::sml::back::process<>** object and using this to "post" the event to the queue, but this would be useless from an ASIO handler as this by default would not be invoked from an action. I suppose a way around this is to capture the callable into the timer handler with a lambda, like this:

    // Some pseudo code (this would all be in one class):

    // Transition table
    "idle"_s + event<Wait> / start_waiting = "waiting"_s

    // Events
    struct Wait { std::chrono::seconds duration; };
    struct Cancel {};
    struct Expire {};

    // Actions
    std::function<void(Wait const&, boost::sml::back::process<Cancel, Expire>)> start_waiting =
      [this] (Wait const& e, boost::sml::back::process<Cancel, Expire> p) {
        run_timer(e, p);
    };

    // Private function
    void run_timer(Wait const& e, boost::sml::back::process<Cancel, Expire>& p) {
      m_timer->expires_after(e.duration);

      auto timerHandler = [&p] (asio::error_code const& e) {
        if (e == asio::error::operation_aborted)
          p(Cancel{});
        else
          p(Expire{});
      };

      timer->async_wait(timerHandler);
    }

But this feels like a bit of a botch.

(3) The last thing that worries me is how the state machine will handle threads. Obviously the timer handler will be executed in its own thread. If that posts an event to the queue of the FSM, will that event be processed by the same thread that posted it? I'm assuming yes, because I can't see any mentions of threads (other than thread safety) in the header. This will dictate how I go about managing the threads' lifetime.

Any tips on alternative ways to architect this, and their pros and cons, would be of great help.

  [1]: https://boost-experimental.github.io/sml/index.html
  [2]: https://github.com/ubeh/fsm_examples/

**Comment by madf** [comment]
(1) When you deal with Boost.ASIO you are almost always bound to use shared pointers. The reason is that your data structures must outlive the I/O context, and there are very limited cases when you can guarantee it without using shared pointers. E.g. when all ASIO lives inside a single class (but beware of construction/destruction) order.

(2) Consider the following example:
```c++
#include "sml.hpp"

#include <boost/asio.hpp>
#include <boost/asio/system_timer.hpp>

#include <chrono>

namespace pls = std::placeholders;

struct Wait
{
    std::chrono::seconds duration;
};
struct Cancel {};
struct Expire {};

struct TEBase
{
    virtual void start(const Wait& ev) = 0;
};

struct States
{
    States(TEBase& t) : te(t) {}

    auto operator()()
    {
        using namespace boost::sml;
        return boost::sml::make_transition_table(*"idle"_s + event<Wait> / std::bind(&TEBase::start, &te, pls::_1) = "waiting"_s);
    }

    TEBase& te;
};

struct TE : TEBase
{
    TE();

    void run();

    void start(const Wait& ev) override;

    boost::asio::io_service ioc;
    boost::asio::system_timer timer;
    boost::sml::sm<States> sm;
};

TE::TE()
    : timer(ioc),
      sm(States{*this})
{
}

void TE::run()
{
    sm.process_event(Wait{std::chrono::seconds(1)});
    ioc.run();
}

void TE::start(const Wait& ev)
{
    timer.expires_from_now(ev.duration);
    timer.async_wait([this](const boost::system::error_code& ec)
    {
        if (ec == boost::asio::error::operation_aborted)
            sm.process_event(Cancel{});
        else
            sm.process_event(Expire{});
    });
}

int main()
{
    TE te;
    te.run();
    return 0;
}
```
I had to use `TEBase` with virtual `start` to break cyclic dependency between `States` and `TE`. Without `TEBase` they both must know full type of each own. The example is compilable and workable.

You may notice that in this example I don't use shared pointers. If `boost::asio::io_service` lives in a different class `TEBase` must inherit from `std::enable_shared_from_this` and you should bind methods to `shared_from_this()` - this is a standard practice in ASIO.

(3) SML does not fire its own threads, all processing happens from the thread where the event happens. You may need some synchronization if you fire events from different threads. The documentation says that SML itself is not thread-safe, bot you may specify thread safety policy and provide a mutex.

**Comment by pesho-t** [comment]
@madf, thanks for the detailed answer.

The more I see the approach in (2) the more I am getting to like it. It is similar to [this one](https://github.com/ubeh/fsm_examples) I pointed to (in the **fsm** directory). I think I'll stick to it.

With regards to (3), I was afraid of this. It means that doing certain things from the ASIO callback (such as invoking a user-provided callback) is dangerous. But this is out of scope for this question so I shan't continue rambling on.

Thanks again!
