### ISSUE TITLE
VisualStudio intellisense bug using SML

### ISSUE THREAD

**Issue by biomed12** [boost-experimental/sml#329]
When I try to compile my test code on VS2019, the intellisense underlines the code attached. Interestingly the code compiles and runs normally.

![intellibug](https://user-images.githubusercontent.com/18486800/79703147-8d062080-82b2-11ea-99c8-e11581fbb1d9.PNG)

**Comment by ekigwana** [comment]
Check the C++ standard for the project

**Comment by biomed12** [comment]
> Check the C++ standard for the project

The same for C++ 17 and 14.

**Comment by ekigwana** [comment]
> > Check the C++ standard for the project
> 
> The same for C++ 17 and 14.

You never stated what the error was.

**Comment by biomed12** [comment]
![intellibug](https://user-images.githubusercontent.com/18486800/79705328-f4759d80-82bd-11ea-8929-0572f77ec33c.PNG)

**Comment by biomed12** [comment]
Finally, I found the problem. I was using the release version of the library. But, the latest release does not contain some macros so I used the sml.hpp file which is located at the development branch.
