### ISSUE TITLE
Can't run "Hello World" example on visual studio

### ISSUE THREAD

**Issue by elopez7** [boost-experimental/sml#342]
Hi, I am trying out sml, but I am running into an issue that I can't solve.
The code I am using is Hello World from the examples page.

I am using visual studio 2019
I specified C++14 in the project settings.

The errors I am getting are:
`too few arguments for alias template "boost::sml::v1_1_0::sm" main.cpp	73	
template parameter pack not at end of parameter list	sml.hpp	1998`

I am just using the header file I downloaded from the main repo.
I do not have any of the boost libraries on my machine.

I am also providing a screenshot of where the errors are happening.

Here is the code from the example I am using.

`#include <cassert>
#include "sml.hpp"`

`namespace sml = boost::sml;`

`namespace {
	struct release {};
	struct ack {};
	struct fin {};
	struct timeout {};`

	`const auto is_ack_valid = [](const ack&) { return true; };
	const auto is_fin_valid = [](const fin&) { return true; };`

	`const auto send_fin = [] {};
	const auto send_ack = [] {};`

`#if !defined(_MSC_VER)
	struct hello_world {
		auto operator()() const {
			using namespace sml;
			return make_transition_table(
				*"established"_s + event<release> / send_fin = "fin wait 1"_s,
				"fin wait 1"_s + event<ack>[is_ack_valid] = "fin wait 2"_s,
				"fin wait 2"_s + event<fin>[is_fin_valid] / send_ack = "timed wait"_s,
				"timed wait"_s + event<timeout> / send_ack = X
			);
		}
	};
}`

`int main() {
	using namespace sml;

	sm<hello_world> sm;
	static_assert(1 == sizeof(sm), "sizeof(sm) != 1b");
	assert(sm.is("established"_s));

	sm.process_event(release{});
	assert(sm.is("fin wait 1"_s));

	sm.process_event(ack{});
	assert(sm.is("fin wait 2"_s));

	sm.process_event(fin{});
	assert(sm.is("timed wait"_s));

	sm.process_event(timeout{});
	assert(sm.is(X));  // released
}
#else
	class established;
	class fin_wait_1;
	class fin_wait_2;
	class timed_wait;

	struct hello_world {
		auto operator()() const {
			using namespace sml;
			return make_transition_table(
				*state<established> +event<release> / send_fin = state<fin_wait_1>,
				state<fin_wait_1> +event<ack>[is_ack_valid] = state<fin_wait_2>,
				state<fin_wait_2> +event<fin>[is_fin_valid] / send_ack = state<timed_wait>,
				state<timed_wait> +event<timeout> / send_ack = X
			);
		}
	};
}`

`int main() {
	using namespace sml;

	sm<hello_world> sm;
	assert(sm.is(state<established>));

	sm.process_event(release{});
	assert(sm.is(state<fin_wait_1>));

	sm.process_event(ack{});
	assert(sm.is(state<fin_wait_2>));

	sm.process_event(fin{});
	assert(sm.is(state<timed_wait>));

	sm.process_event(timeout{});
	assert(sm.is(X));  // released
}
#endif`

Thank you in advance for the help.
![Capture](https://user-images.githubusercontent.com/8985647/82364755-b31bff00-99dd-11ea-84e9-b3fe1ce815c6.JPG)

**Comment by elopez7** [comment]
I tried to make the code format properly on the page, but it wouldn't I apologize.

**Comment by elopez7** [comment]
It was entirely user error, I didn't notice the header file had been updated.

**Comment by fawdlstty** [comment]
I encountered the same error, how to resolve it?
