### ISSUE TITLE
[question] transition evaluation order

### ISSUE THREAD

**Issue by redboltz** [boost-experimental/sml#72]
I sometimes want to use if/else branch on guards.
Does the elements of the make_transition_table evaluate top to bottom?
If it does, I can implement if/else branch using no guard branch as follows:

```cpp
#include <iostream>
#include <boost/sml.hpp>
namespace sml = boost::sml;
struct Prop { int val; };
struct Event1 {};
struct Simple {
    auto operator()() const noexcept {
        using namespace sml;
        return make_transition_table(
            * "State1"_s + event<Event1> [([](Prop& p){ return p.val == 1;})]
            / [](auto const&) { std::cout << "Action1" << std::endl;} = "State1"_s // val == 1
            , "State1"_s + event<Event1>
            / [](auto const&) { std::cout << "Action2" << std::endl;} = "State1"_s // else
            , "State1"_s + on_entry<_> / [](auto const&){ std::cout << "on_entry" << std::endl; }
            , "State1"_s + on_exit<_> / [](auto const&){ std::cout << "on_exit" << std::endl; }
        );
    }
};
int main() {
    Prop p{1};
    sml::sm<Simple> sm{p};
    sm.process_event(Event1{});
    p.val = 2;
    sm.process_event(Event1{});
}
```

BTW, my friend implemented daily update sml on his online compiling environment named Wandbox.

http://melpon.org/wandbox/permlink/lKfepkCS4tGl6WB0

**Comment by krzysztof-jusiak** [comment]
It's a great question and yea the order is guaranteed to be from top to bottom so the example will work as expected. The order guarantee was required for handling exceptions and generic events but it might be used for else branches as well which, additionally, speeds up things as guard doesn't have to be checked twice (I'm doing it myself and sml is tested against that too).

Yes, I've seen it. Thank you! I love Wandbox, IMHO it's the best online compiler. I'm using it in boost.di and boost.sml online documentation too. This way users can check the functionality easily and experiment with it without downloading the library.

**Comment by redboltz** [comment]
Thank you! It's ideal behavior to implementation for if/else branch. Boost.MSM evaluates bottom to top by some reason. sml is more natural :)
