### ISSUE TITLE
Anonymous transition from outer state that has sub machine should wait sub machine's termination

### ISSUE THREAD

**Issue by redboltz** [boost-experimental/sml#74]
See the following diagram:

```
Sm

+------------+       +---------+
|*state:Sub  |------>| State2  |
|            |       |         |
+------------+       +---------+


Sub

+------------+  Event1
|*SubState1  |--------->X
|            |
+------------+
```

UML specification said that Sm's anonymous transition invokes when Sub arrives at terminate state.

``` cpp
#include <cassert>
#include <boost/sml.hpp>
namespace sml = boost::sml;
struct Event1 {};
struct Sub {
    auto operator()() const noexcept {
        using namespace sml;
        return make_transition_table(
            * "SubState1"_s + event<Event1> = X
        );
    }
};
struct Sm {
    auto operator()() const noexcept {
        using namespace sml;
        return make_transition_table(
            * state<Sub> = "State2"_s
        );
    }
};
int main() {
    using namespace sml;
    sm<Sm> sm;
    assert(sm.is(state<Sub>)); // actual state is "State2"_s
    assert(sm.is<Sub>("SubState1"_s));
    sm.process_event(Event1{}); assert(sm.is("State2"_s));
}
```

http://melpon.org/wandbox/permlink/dk6BWkG5oh60EiIP

However, it seems that anonymous transition invoked before Sub is terminated.

**Comment by redboltz** [comment]
> UML specification said that Sm's anonymous transition invokes when Sub arrives at terminate state.

Strictly speaking, UML specification said that Sm's anonymous transition invokes when Sub arrives at final state, not terminate pseudo state.

http://www.uml-diagrams.org/state-machine-diagrams.html#final-state
http://www.uml-diagrams.org/state-machine-diagrams.html#terminate-pseudostate

But I'm not sure SML should distinguish them or not.

**Comment by krzysztof-jusiak** [comment]
This one is interesting. Thanks for pointing it out @redboltz. I wasn't aware of that. I will check it with UML and Boost.MSM and try to fix it ASAP.

**Comment by redboltz** [comment]
Here is an example of the state machine:
http://redboltz.wikidot.com/exit-point-pseudo-state

AFAIK, Boost.MSM doesn't support the first diagram, but it supports the second one that is using exit point pseudo state with anonymous transition:
http://melpon.org/wandbox/permlink/aEJk9ZK5dSrqXKNH

Even if outer state machine's current state has an anonymous transition, it waits for reaching inner sub machine's state transition to the exit point pseudo state.

**Comment by krzysztof-jusiak** [comment]
Thanks @redboltz for the examples. It would be really valuable to have entry/exit pseudo states. They are on my list to implement ASAP.

**Comment by krzysztof-jusiak** [comment]
@redboltz do you happen to know, as I can't find it the UML spec, what about the case when sub machine has multiple orthogonal regions and only one of them is in final/terminate pseudo state?
Should the anonymous transition happen only if all regions are done or it's enough that one will be finished?

**Comment by krzysztof-jusiak** [comment]
Implemented by https://github.com/boost-experimental/sml/commit/c10e541869c73c03aac246aad8b6a123636088d4

In the current version, all orthogonal regions have to be in a terminate state in order to anonymous transition to happen.

**Comment by redboltz** [comment]
I've checked UML 2.5 specification.
http://www.omg.org/spec/UML/2.5/PDF/

In the following section:
**14.2.3.8.3 Completion Transitions and completion events**

I found the following sentence:

if the State is a composite State, all its orthogonal Regions have reached a FinalState

So, I think that your current implementation satisfied UML 2.5 spec.

**Comment by redboltz** [comment]
I think that the anonymous transition from the parent state that have composite state or sub machine state is a completion transition.

**Comment by krzysztof-jusiak** [comment]
Thanks @redboltz for checking it for me. I find UML 2.5 spec quite hard to deal with. It's really subtle.
Nevertheless, after deeper look, it seems like you are right and the implementation is fine. Yay!
