### ISSUE TITLE
[question] How to define states that have the same sub-machine

### ISSUE THREAD

**Issue by redboltz** [boost-experimental/sml#75]
According to the following document, I can use the notation `state<Sub>` to define sub-machine state.

http://boost-experimental.github.io/sml/examples/index.html#composite

UML allows defining multiple states that have the same sub-machine state as follows:

```
Sm

+------------+ Event2  +------------+
|*State1:Sub |-------->| State2:Sub |
|            |         |            |
+------------+         +------------+


Sub

+------------+  Event1
|*SubState1  |--------->X
|            |
+------------+
```

How to write it on SML?

**Comment by krzysztof-jusiak** [comment]
Sorry for the late reply, I was off for a few days.
Anyway, it's a great point @redboltz.

Having 2 different states for the same composite is totally possible by the back end, however,
there is no syntax for the front end yet. I'm currently brainstorming how it can be done.

Ideas so far...

```cpp
1.   "sub1"_s|(sub)_ = "sub2"_s|(sub)_
2.   "sub1"_s.sm<sub>() = "sub2"_s.sm<sub>()
3.  ...
```

**Comment by redboltz** [comment]
The second one is nice for me.

**Comment by krzysztof-jusiak** [comment]
Yea, the second one seem to be the best option, however, I would really like to have something like that
```cpp
"sub state"_s<sub>
```
but it seems to be impossible to implement, though :(

**Comment by redboltz** [comment]
The issue is also related to `is()` member function.

```cpp
sm.is("State1"_s);
sm.is("sub1"_s.sm<sub>());
sm.is("sub2"_s.sm<sub>());
```

I'm not sure sm.is() and history state. If `sub` has history state, "sub1"_s and "sub2"_s have different history state.

As you mentioned the followin comment, `"sub1"_s.sm<sub>()` and `"sub2"_s.sm<sub>()`'s `sub` have a different last (historical) state member variables.

https://github.com/boost-experimental/sml/issues/76#issuecomment-258813330

**Comment by krzysztof-jusiak** [comment]
Great point @redboltz. I noticed it myself when plenty of tests failed due to that.
As you already mentioned `is` will have to be changed too.

Ideally, it would be something like that or similar...
```cpp
sm.is<"sub1"_s<sub>>("state1"_s);
sm.is<"sub2"_s<sub>>("state2"_s);
```

**Comment by krzysztof-jusiak** [comment]
Should be fixed by https://github.com/boost-experimental/sml/commit/0c49d1325677783f1e9853dd4871765b709b7deb.

Thanks again @redboltz for reporting issue!

The following syntax is now allowed along the old one.
```cpp
"sub state 1"_s.sm<sub>() + event<e1> = "sub state 2"_s.sm<sub>()
```

`is` was generalized to support both cases too.
```cpp
assert(sm.is(X));
assert(sm.is<decltype("sub state 1"_s.sm<sub>())>("idle"_s));
```

Full example below...

```cpp
  struct sub {
    auto operator()() const noexcept {
      using namespace sml;
      // clang-format off
      return make_transition_table(
        *idle + event<e1> = X
      );
      // clang-format on
    }
  };

  struct c {
    auto operator()() const noexcept {
      using namespace sml;
      // clang-format off
      return make_transition_table(
        *"state a"_s.sm<sub>() + event<e2> = "state b"_s.sm<sub>(),
         "state b"_s.sm<sub>() + event<e3> = X
      );
      // clang-format on
    }
  };

  using namespace sml;
  sm<c> sm;
  expect(sm.is("state a"_s.sm<sub>()));
  expect(sm.is<decltype("state a"_s.sm<sub>())>(idle));
  expect(sm.is<decltype("state b"_s.sm<sub>())>(idle));

  sm.process_event(e1{});
  expect(sm.is("state a"_s.sm<sub>()));
  expect(sm.is<decltype("state a"_s.sm<sub>())>(X));
  expect(sm.is<decltype("state b"_s.sm<sub>())>(idle));

  sm.process_event(e2{});
  expect(sm.is("state b"_s.sm<sub>()));
  expect(sm.is<decltype("state a"_s.sm<sub>())>(X));
  expect(sm.is<decltype("state b"_s.sm<sub>())>(idle));

  sm.process_event(e1{});
  expect(sm.is("state b"_s.sm<sub>()));
  expect(sm.is<decltype("state a"_s.sm<sub>())>(X));
  expect(sm.is<decltype("state b"_s.sm<sub>())>(X));

  sm.process_event(e3{});
  expect(sm.is(X));
```

**Comment by redboltz** [comment]
Thank you for implementing. It works perfectly fine!
