### ISSUE TITLE
dispatching sub-machine's process event at the action in the same instance

### ISSUE THREAD

**Issue by redboltz** [boost-experimental/sml#76]
I stated using `process` functionality. I noticed that the event generated by `process(Event{})` is not processed on the parent state machine.

See the following code:

http://melpon.org/wandbox/permlink/JFBqnPUuSKtKoo4e

``` cpp
#include <iostream>
#include <boost/sml.hpp>

namespace sml = boost::sml;

struct Event1 {};
struct Event2 {};
struct Event3 {};
struct Event4 {};
struct ChainedParentEvent {};
struct ChainedSubEvent {};

struct Sub {
    auto operator()() const noexcept {
        using namespace sml;
        return make_transition_table(
            * "SubState1"_s + event<Event1> / process(ChainedParentEvent{}) // ChainedParentEvent is NOT dispatched by Sm
            , "SubState1"_s + event<Event2> / process(ChainedSubEvent{})    // ChainedSubEvent is dispatched by Sub
            , "SubState1"_s + event<ChainedSubEvent> / [] { std::cout << "sub action" << std::endl; }
        );
    }
};
struct Sm {
    auto operator()() const noexcept {
        using namespace sml;
        return make_transition_table(
            * state<Sub> + event<Event3> / process(ChainedParentEvent{})  // ChainedParentEvent is not dispatched by Sm
            , state<Sub> + event<Event4> / process(ChainedSubEvent{})     // ChainedSubEvent is dispatched by Sub 
            , state<Sub> + event<ChainedParentEvent> / [] { std::cout << "parent action" << std::endl; }
        );
    }
};
int main() {
    using namespace sml;
    sm<Sm> sm;
    sm.process_event(Event1{});
    sm.process_event(Event2{});
    sm.process_event(Event3{});
    sm.process_event(Event4{});
}
```

The event processed in Sm's action is processed by both Sm and Sub, but the event processed in Sub's action is processed by Sub but isn't processed in Sm.

I believe that I should be processed both Sm and Sub.

**Comment by krzysztof-jusiak** [comment]
Yea, process is per state machine, hence the observed behavior.
Anyway, it will be refactored when process will be replaced by the queue event.

BTW. It's the same scenario with defer events, though. So, in a situation when an event is deferred by the composite it won't be handled by the top state machine. Should it be, though?

**Comment by redboltz** [comment]
> Yea, process is per state machine, hence the observed behavior.

Hmm, do you mean the front-end of the state machine? If it is, there are two state machines. The first one is Sm that contains Sub, and the second one is Sub. But the back-end is only one. That is `sm<Sm> sm;`. The concept of `process()` is a little complicated. Because `process()` is written in the front-end but it processes an event via back-end.

> Anyway, it will be refactored when process will be replaced by the queue event.

I think that I want to some functionality that I can process (or post) an event from Sub state machine to Parent (including Sub) state machine.

> BTW. It's the same scenario with defer events, though. So, in a situation when an event is deferred by the composite it won't be handled by the top state machine. Should it be, though?

I think that it should be. The event is checking from innermost state to outer states, if the checking process finds `defer`, then enqueue to defer-queue. I think that defer-queue should be owned by each back-end.


IMHO, event queue and defer queue should be owned by the back-end of the state machine, not front-end. If it is, we can write process event code in the Sub and the event will be processed by it's parent. That doesn't mean Sub depends on its parent because states and events are orthogonal concept.

**Comment by krzysztof-jusiak** [comment]
> Hmm, do you mean the front-end of the state machine? If it is, there are two state machines. The first one is Sm that contains Sub, and the second one is Sub. But the back-end is only one. That is `sm<Sm> sm;`. The concept of `process()` is a little complicated. Because `process()` is written in the front-end but it processes an event via back-end.

Yea, it's a bit confusing, so let me explain how it's implemented.
There is a one back end, as you mentioned, however, it contains 2 different objects (aka sub machines); one is the top state machine and the other one is the sub state machine. Some data is stored in the the back-end sm like dependencies and policies and specific stuff to a state machine (defer events for example) is stored per state machine.

```cpp
template<class TopSM>
back::sm {
  tuple<sm_impl<TopSM>, sm_impl<sub_sm>> subs_; // sub_sm taken from the transition table
  dependencies deps_; // injected via ctor
  policies policies_;
};

template<class T>
back::sm_impl {
  int current_state_[regions];
  decltype(declval<T>()()) transitions; // states, gurad, actions, events
  defer_queue defer_; // defer events
};
```

Now, front-end process it's a bit of a hack as it just a call of process_event on the sm which was called from...
```cpp
template<class TEvent>
struct process : action_base {
    template <class T, class TSM, class TDeps, class TSubs>
    void operator()(const T&, TSM& sm, TDeps& deps, TSubs& subs) {
      sm.process_event(event, deps, subs);
    }
   TEvent event;
};
```

which is unfortunate and will be changed to a queue as discussed before.

Additionally, this queue might be on the back::sm level (in deps basically) or on back::sm_impl level (like defer events). 

* sm level -> global per back-end (so process from sub will trigger process in the top)
* sm_impl level -> local to the sub machine (process from sub won't trigger process in the top <- current implementation)

All in all, with the queuing instead of processing directly, the behaviour might be easily adopted, depending on where the queue will be stored.

> I think that I want to some functionality that I can process (or post) an event from Sub state machine to Parent (including Sub) state machine.

I agree, I have a case when I would really like to inform that the sub has finished processing. It can't be done easily with the current implementation (might be workaround, though).

> IMHO, event queue and defer queue should be owned by the back-end of the state machine, not front-end. If it is, we can write process event code in the Sub and the event will be processed by it's parent. That doesn't mean Sub depends on its parent because states and events are orthogonal concept.

Agree, and they are owned by the back-end. front-end is just a trigger the back-end to do something with it. For example, defer (front-end), when called triggers to store an even in the queue owned by back-end.

```cpp
struct defer : action_base {
  template <class TEvent, class TSM, class TDeps, class TSubs>
  void operator()(const TEvent &event, TSM &sm, TDeps &, TSubs &) {
    sm.defer_.push(event);
  }
};
```

**Comment by kptlronyttcna** [comment]
Is there any updates on this?

**Comment by madmongo1** [comment]
I came across this too. The inner state should absolutely inform the outer state of the event. The UML specification demands that both the inner and outer state are aware of the exit event. Otherwise the outer state cannot take action on it.

**Comment by Bagira80** [comment]
The first reference to commit [d88dcd5](https://github.com/Bagira80/sml/commit/d88dcd58f2fb8d9208a3ea571ae531e1976bba8a) contained a warning, so ignore that. The second commit [fc50d44](https://github.com/Bagira80/sml/commit/fc50d44ea9777a527762b7a601be3c427cc5b34e) is the correct fix.

**Comment by Bagira80** [comment]
As you might have noticed, my second commit had some small errors, too, and was also missing tests.
The last commit [44d8f57](https://github.com/boost-experimental/sml/commit/44d8f57681b96c327e7a61718902467f9c3f7017) however should work fine, now, and additionally has tests.

**Comment by madmongo1** [comment]
Awesome news. I'll continue my gobliz game and see where we get.

**Comment by aliasdevelopment** [comment]
Please note that the test/ft/actions_process.cpp has been changed. The test does not support forward of sub state events to the parent state. The test only performs sub state to sub state process event.
