### ISSUE TITLE
VC++ 2015 : sml.hpp(864): warning C4244: '=': conversion from 'int' to 'unsigned char', possible loss of data

### ISSUE THREAD

**Issue by gicutza** [boost-experimental/sml#77]
VC++ 2015 : sml.hpp(864): warning C4244: '=': conversion from 'int' to 'unsigned char', possible loss of data

**Comment by gicutza** [comment]
sml.hpp(1812): warning C4244: 'argument': conversion from 'int' to 'const unsigned char', possible loss of data
sml.hpp(1962): warning C4244: 'argument': conversion from 'int' to 'const unsigned char', possible loss of data

**Comment by krzysztof-jusiak** [comment]
Should be fixed by https://github.com/boost-experimental/sml/commit/e401395933b19870cf1cac59de3adb935ca98468
[Boost].SML is now compiling with /W4 /WX on MSVC-2015.
