### ISSUE TITLE
VC++ 2015: include\boost\sml.hpp(1121): warning C4458: declaration of 'sm_t' hides class member

### ISSUE THREAD

**Issue by gicutza** [boost-experimental/sml#78]
VC++ 2015: include\boost\sml.hpp(1121): warning C4458: declaration of 'sm_t' hides class member

**Comment by krzysztof-jusiak** [comment]
Should be fixed by https://github.com/boost-experimental/sml/commit/e401395933b19870cf1cac59de3adb935ca98468
[Boost].SML is now compiling with /W4 /WX on MSVC-2015.
