### ISSUE TITLE
on_exit requires namespace qualification on g++

### ISSUE THREAD

**Issue by redboltz** [boost-experimental/sml#80]
I got a compile error as follows when I use `on_exit` without namespace qualification on g++:

```
prog.cc: In member function 'auto sub::operator()() const':
prog.cc:15:25: error: reference to 'on_exit' is ambiguous
             , "ss1"_s + on_exit<_>  / [](auto const&) { std::cout << "ss1 on exit" << std::endl; }
```

Here is the code:

```cpp
#include <iostream>
#include "boost/sml.hpp"

namespace sml = boost::sml;

struct e1 {};

struct sub {
    auto operator()() const noexcept {
        using namespace sml;
        // clang-format off
        return make_transition_table(
            *"ss1"_s + event<e1> = X
            , "ss1"_s + on_entry<_> / [](auto const& ev) { std::cout << "ss1 on entry" << std::endl; }
            , "ss1"_s + sml::on_exit<_>  / [](auto const& ev) { std::cout << "ss1 on exit" << std::endl; }
        );
        // clang-format on
    }
};

int main() {
    using namespace sml;
    sm<sub> sm;
}
```

clang++ with namespace qualification OK
http://melpon.org/wandbox/permlink/LXqtvpQuIpZHSBO8

clang++ without namespace qualification OK
http://melpon.org/wandbox/permlink/RL4Dq3gma8CgAMMT

g++ with namespace qualification OK
http://melpon.org/wandbox/permlink/8jC5izld5AQbN0IH

g++ without  namespace qualification ERROR
http://melpon.org/wandbox/permlink/Sz5mbVMJI7NpagMm

I'm not sure that is sml's problem or g++'s problem.

**Comment by krzysztof-jusiak** [comment]
It seems to be an issue in libstdc++ provided with GCC because 'on_exit' from `stdlib.h` is included which is not guarded by 'std' namespace :/ I will report an issue against libstdc++.

**Comment by krzysztof-jusiak** [comment]
I created a bug for gcc/libstdc++ here -> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78483

**Comment by redboltz** [comment]
Thank you for following up the issue.

Until gcc will fix the issue, I use `using sml::on_exit;` for workaround as follows:

http://melpon.org/wandbox/permlink/Ni1CeSqfj0kfvv8c

The program can compile with both g++ and clang++, also keep state machine DSL beautiful.

**Comment by krzysztof-jusiak** [comment]
Closing to clean up issues, gcc seems not to be willing to fix it, though :/

**Comment by jonesmz** [comment]
There are several examples that use sml:: for on_exit and on_entry, and I did not understand why.

Can those examples be improved to document the reason ?
