### ISSUE TITLE
Guards execution, when used as a logical expression

### ISSUE THREAD

**Issue by omicronns** [boost-experimental/sml#97]
When you create logical guard expression, all guards are getting executed even if it is not needed due to expression nature.

    namespace smt {

        using namespace boost::sml;

        struct s1;
        struct s2;

        struct e {};

        auto g1 = []() {
            return false;
        };
        auto g2 = []() {
            return true;
        };

        struct tt {
            auto operator()() {
                return make_transition_table(
                    *state<s1> +event<e>[g1 && g2] = state<s2>
                );
            }
        };

    }

    int main() {
        using namespace boost::sml;
        sm<smt::tt> s;
        s.process_event(smt::e());
        return 0;
    }

Both g1 and g2 are getting executed, even that at the point of g1 execution it is obvious that whole expression will evaluate to false.

**Comment by hovren** [comment]
I still have this issue on version 1.1.3 using Visual Studio 2019.
Tried by running the same code above.
