### ISSUE TITLE
Forward-declaring state machine struct

### ISSUE THREAD

**Issue by ukreator** [boost-experimental/sml#99]
Is it possible to hide a state machine inside a class by means of forward declaration? I tried something like this:

```cpp
// header

#include <boost/sml.hpp>
#include <memory>

struct StateMachine;

class MyClass {
public:
    void someOperation();
private:
    std::unique_ptr<boost::sml::sm<StateMachine>> _sm;
};
```

but it fails to compile in .cpp files which do not correspond to this class implementation with the following error:

```
sml.hpp:1525:41: error: no type named 'type' in 'boost::sml::v1_1_0::aux::enable_if<false, int>'; 'enable_if' cannot be used to disable this declaration
template <class T, __BOOST_SML_REQUIRES(concepts::composable<typename T::sm>::value)>
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jonpe960** [comment]
+1

I'm currently doing this:

Class definition:

```
class DHCPClient {
private:
  boost::shared_ptr<void>   fsm_;
public:
```


Constructor:

```
DHCPClient::DHCPClient()  {

  fsm_ = boost::shared_ptr<msm::sm<DHCPClientSM>> (new msm::sm<DHCPClientSM>{this});
```

And in each member function of my class where I need to access the statemachine:

```
void DHCPClient::DHCPTest() {
  boost::shared_ptr<msm::sm<DHCPClientSM>> sm = 
    boost::static_pointer_cast<msm::sm<DHCPClientSM>>(fsm_); 

  cout << "DHCPTest" << endl;
  sm->process_event(e3{});
}
```


I'm sure there must be a more elegant way of doing this. 


I'm working on a DHCP client for an embedded system where I can have multiple clients running in parallell which obviously means that I need an instance of the state machine for each "DHCPClient" object. I also need callbacks from the state machine into the appropriate DHCPClient-object that, for example, would switch to a raw socket for broadcasting or another one for listening on updates.

**Comment by codentary** [comment]
@jonasblixt Did you ever find a "more elegant way", to not have to cast every time you need to use the `fsm_` ?

**Comment by ukreator** [comment]
@codentary the approach from my initial comment works fine for a few years already

**Comment by codentary** [comment]
You mean `std::unique_ptr<boost::sml::sm<StateMachine>> _sm;` works just by forward declaring the `StateMachine`? For me it doesn't. Do you pass `MyClass` as a parameter to the sm on instantiation?

**Comment by ukreator** [comment]
@codentary you can use something like this if you want to hide sml headers:

```c++

// header

class YourClass  {
    // internal struct to hide boost::sml from this header
    struct StateMachineWrapper;

public:
    void handleSomeEvent();
private:
    std::unique_ptr<StateMachineWrapper> _sm;
    friend class StateMachineImpl;
};


// cpp file

class StateMachineImpl {
   auto operator()() {  return make_transition_table(...); }
};

struct YourClass::StateMachineWrapper {
    explicit StateMachineWrapper(YourClass* owner) : impl(owner) {}
    boost::sml::sm<StateMachineImpl> impl;
};

void YourClass::handleSomeEvent() {
    _sm->impl.process_event(Event{});
}

```
